services:
  - type: web
    name: multi-author-blog
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://multi-author-blog.onrender.com

